# Generated by Django 5.2.8 on 2025-12-01 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_espaciocurricular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de actividad', max_length=100, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción del tipo de actividad')),
                ('tipo_dedicacion', models.CharField(choices=[('IP', 'Interacción Pedagógica (IP)'), ('TA', 'Trabajo Autónomo (TA)')], help_text='Tipo de dedicación de la actividad', max_length=5)),
                ('modalidad_trabajo', models.CharField(choices=[('GRU', 'Trabajo en Grupo'), ('IND', 'Trabajo Individual')], help_text='Modalidad de trabajo de la actividad', max_length=5)),
            ],
            options={
                'verbose_name': 'tipo de actividad',
                'verbose_name_plural': 'tipos de actividades',
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('TIT', 'Titular'), ('ADJ', 'Adjunto'), ('JTP', 'Jefe de Trabajos Prácticos'), ('AYU', 'Ayudante')], help_text='Categoría docente', max_length=5)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docente', to=settings.AUTH_USER_MODEL)),
                ('espacio_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docente', to='academics.espaciocurricular')),
            ],
            options={
                'verbose_name': 'asignación de docente',
                'verbose_name_plural': 'asignaciones de docentes',
                'db_table': 'asignacion_docente',
                'unique_together': {('docente', 'espacio_curricular', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de la actividad', max_length=255)),
                ('horas', models.PositiveIntegerField(default=0, help_text='Cantidad total de horas asignadas a esta actividad')),
                ('asignacion_docente', models.ForeignKey(help_text='Docente y espacio curricular asociados a esta actividad', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='planning.asignaciondocente')),
                ('tipo_actividad', models.ForeignKey(help_text='Tipo de actividad', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='planning.tipoactividad')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'db_table': 'actividad',
            },
        ),
    ]
