# Generated by Django 6.0.2 on 2026-02-12 23:55

import django.core.validators
import django.db.models.deletion
import planning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de actividad', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de actividad (opcional)', null=True)),
                ('tipo_dedicacion', models.CharField(choices=[('IP', 'Interacción Pedagógica (IP)'), ('TA', 'Trabajo Autónomo (TA)')], default='TA', help_text='Tipo de dedicación de la actividad', max_length=5)),
                ('modalidad_trabajo', models.CharField(blank=True, choices=[('GRU', 'Trabajo en Grupo'), ('IND', 'Trabajo Individual')], help_text='Modalidad de trabajo de la actividad (opcional)', max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'tipo de actividad',
                'verbose_name_plural': 'tipos de actividades',
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_academico', models.PositiveIntegerField(help_text='Año académico al que pertenece el programa', validators=[django.core.validators.MinValueValidator(1939)])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del programa')),
                ('plan_estudio_ec', models.ForeignKey(help_text='Plan de estudio y espacio curricular asociados al programa', on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='academics.planestudioec')),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de la actividad', max_length=255)),
                ('horas', models.PositiveIntegerField(default=0, help_text='Cantidad total de horas asignadas a esta actividad', validators=[django.core.validators.MinValueValidator(0)])),
                ('programa', models.ForeignKey(help_text='Programa asociado a esta actividad', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='planning.programa')),
                ('tipo_actividad', models.ForeignKey(default=planning.models.get_tipo_actividad_otros, help_text="Tipo de actividad (según tipificación establecida). Por defecto: 'Otros'", on_delete=django.db.models.deletion.SET_DEFAULT, related_name='actividades', to='planning.tipoactividad')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('TIT', 'Titular'), ('ADJ', 'Adjunto'), ('ASO', 'Asociado'), ('JTP', 'Jefe de Trabajos Prácticos'), ('AY1', 'Ayudante de 1°'), ('AY2', 'Ayudante de 2°')], help_text='Categoría docente', max_length=5)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la asignación docente está activa')),
                ('docente', models.ForeignKey(help_text='Docente asignado a espacio curricular', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_docente', to=settings.AUTH_USER_MODEL)),
                ('espacio_curricular', models.ForeignKey(help_text='Espacio curricular al que está asignado el docente', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_docente', to='academics.espaciocurricular')),
            ],
            options={
                'verbose_name': 'asignación de docente',
                'verbose_name_plural': 'asignaciones de docentes',
                'db_table': 'asignacion_docente',
                'constraints': [models.UniqueConstraint(fields=('docente', 'espacio_curricular'), name='unique_asignacion_docente')],
            },
        ),
        migrations.AddConstraint(
            model_name='programa',
            constraint=models.UniqueConstraint(fields=('plan_estudio_ec', 'anio_academico'), name='unique_programa_ec_anio'),
        ),
    ]
