# Generated by Django 5.2.8 on 2025-12-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del tipo de actividad (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='modalidad_trabajo',
            field=models.CharField(blank=True, choices=[('GRU', 'Trabajo en Grupo'), ('IND', 'Trabajo Individual')], help_text='Modalidad de trabajo de la actividad (opcional)', max_length=5, null=True),
        ),
    ]
