# Generated by Django 6.0.2 on 2026-02-13 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='anio_academico',
            field=models.PositiveIntegerField(db_index=True, help_text='Año académico al que pertenece el programa', validators=[django.core.validators.MinValueValidator(1939)]),
        ),
    ]
