# Generated by Django 6.0.2 on 2026-02-13 00:19

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_espaciocurricular_codigo_and_more'),
        ('planning', '0002_alter_programa_anio_academico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignaciondocente',
            name='unique_asignacion_docente',
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='vigente_desde',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha desde la cual la asignación está vigente'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='vigente_hasta',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual la asignación estuvo vigente (dejar en blanco si aún está vigente)', null=True),
        ),
        migrations.AddIndex(
            model_name='asignaciondocente',
            index=models.Index(fields=['docente', 'vigente_desde', 'vigente_hasta'], name='idx_asignacion_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='asignaciondocente',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gte', models.F('vigente_desde')), _connector='OR'), name='valid_date_range'),
        ),
        migrations.RemoveField(
            model_name='asignaciondocente',
            name='activo',
        ),
    ]
