# Generated by Django 6.0.2 on 2026-02-13 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_espaciocurricular_codigo_and_more'),
        ('planning', '0003_change_asignacion_temporal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaciondocente',
            options={'verbose_name': 'asignación docente', 'verbose_name_plural': 'asignaciones docentes'},
        ),
        migrations.RemoveConstraint(
            model_name='asignaciondocente',
            name='valid_date_range',
        ),
        migrations.RemoveIndex(
            model_name='asignaciondocente',
            name='idx_asignacion_vigencia',
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='vigente_desde',
            field=models.DateField(help_text='Fecha desde la cual la asignación está vigente'),
        ),
        migrations.AddIndex(
            model_name='asignaciondocente',
            index=models.Index(fields=['docente', 'vigente_desde'], name='asignacion__docente_7d355a_idx'),
        ),
        migrations.AddIndex(
            model_name='asignaciondocente',
            index=models.Index(fields=['espacio_curricular', 'vigente_desde'], name='asignacion__espacio_db3bff_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignaciondocente',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_desde__lte', models.F('vigente_hasta')), _connector='OR'), name='check_valid_temporal_range', violation_error_message='vigente_desde debe ser anterior o igual a vigente_hasta.'),
        ),
    ]
