# Generated by Django 6.0.2 on 2026-02-24 10:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_asignaciondocente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='modalidad_trabajo',
            field=models.CharField(choices=[('IND', 'Trabajo Individual'), ('EQU', 'Trabajo en Equipo')], default='IND', help_text='Modalidad de trabajo de la actividad', max_length=3),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número de unidad dentro del programa', validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.CharField(help_text='Descripción de la unidad', max_length=255)),
                ('programa', models.ForeignKey(help_text='Programa al que pertenece la unidad', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='planning.programa')),
            ],
            options={
                'verbose_name': 'unidad',
                'verbose_name_plural': 'unidades',
                'db_table': 'unidad',
                'ordering': ['programa_id', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='unidades',
            field=models.ManyToManyField(help_text='Unidades del programa asociadas a esta actividad', related_name='actividades', to='planning.unidad'),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('programa', 'numero'), name='unique_unidad_programa_numero'),
        ),
    ]
