# Generated by Django 6.0.2 on 2026-02-24 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_actividad_modalidad_trabajo_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad total de horas asignadas a esta actividad (permite fracciones)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
