# Generated by Django 6.0.2 on 2026-02-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_alter_actividad_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si la actividad está activa (baja lógica).'),
        ),
        migrations.AddField(
            model_name='programa',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el programa está activo (baja lógica).'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si la unidad está activa (baja lógica).'),
        ),
    ]
