# Generated by Django 6.0.2 on 2026-03-09 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_competencia'),
        ('planning', '0007_actividad_activo_programa_activo_unidad_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_fin_ta',
            field=models.DateField(blank=True, help_text='Fecha de fin opcional para actividades TA.', null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_inicio_ta',
            field=models.DateField(blank=True, help_text='Fecha de inicio opcional para actividades TA.', null=True),
        ),
        migrations.CreateModel(
            name='ClaseCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('PLAN', 'Planificada'), ('DICT', 'Dictada'), ('CANC', 'Cancelada')], default='PLAN', max_length=4)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_calendario', to='planning.programa')),
            ],
            options={
                'verbose_name': 'clase de calendario',
                'verbose_name_plural': 'clases de calendario',
                'db_table': 'clase_calendario',
                'ordering': ['programa_id', 'fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActividadAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REC', 'Recuperacion'), ('EXT', 'Extension')], max_length=3)),
                ('motivo', models.CharField(max_length=255)),
                ('horas_ip_extra', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='planning.actividad')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_ajustes_creados', to=settings.AUTH_USER_MODEL)),
                ('clase_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='planning.clasecalendario')),
            ],
            options={
                'verbose_name': 'ajuste de actividad',
                'verbose_name_plural': 'ajustes de actividades',
                'db_table': 'actividad_ajuste',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='clase_calendario',
            field=models.ForeignKey(blank=True, help_text='Clase de calendario asociada (obligatoria para actividades IP).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='planning.clasecalendario'),
        ),
        migrations.CreateModel(
            name='DiaClasePrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_clase', to='planning.programa')),
            ],
            options={
                'verbose_name': 'dia de clase',
                'verbose_name_plural': 'dias de clase',
                'db_table': 'dia_clase_programa',
                'ordering': ['programa_id', 'dia_semana', 'hora_inicio', 'id'],
            },
        ),
        migrations.AddField(
            model_name='clasecalendario',
            name='dia_clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_calendario', to='planning.diaclaseprograma'),
        ),
        migrations.CreateModel(
            name='UnidadCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_rel', to='academics.competencia')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_rel', to='planning.unidad')),
            ],
            options={
                'verbose_name': 'unidad competencia',
                'verbose_name_plural': 'unidades competencias',
                'db_table': 'unidad_competencia',
                'ordering': ['unidad_id', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='diaclaseprograma',
            constraint=models.UniqueConstraint(fields=('programa', 'dia_semana', 'hora_inicio', 'hora_fin'), name='unique_dia_clase_programa_slot'),
        ),
        migrations.AddConstraint(
            model_name='diaclaseprograma',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__isnull', True), ('hora_inicio__isnull', True), ('hora_inicio__lt', models.F('hora_fin')), _connector='OR'), name='check_dia_clase_hora_inicio_menor_hora_fin'),
        ),
        migrations.AddConstraint(
            model_name='clasecalendario',
            constraint=models.UniqueConstraint(fields=('programa', 'fecha'), name='unique_clase_calendario_programa_fecha'),
        ),
        migrations.AddConstraint(
            model_name='unidadcompetencia',
            constraint=models.UniqueConstraint(fields=('unidad', 'competencia'), name='unique_unidad_competencia'),
        ),
    ]
