# Generated by OpenCode on 2026-06-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_actividad_fecha_fin_ta_actividad_fecha_inicio_ta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoactividad',
            name='modalidad_trabajo',
        ),
    ]
