# Generated by OpenCode on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_remove_tipoactividad_modalidad_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='modalidad_trabajo',
            field=models.CharField(
                choices=[('IND', 'Trabajo Individual'), ('EQU', 'Trabajo Grupal')],
                default='IND',
                help_text='Modalidad de trabajo de la actividad',
                max_length=3,
            ),
        ),
    ]
