# Generated by Django 6.0.2 on 2026-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_seed_ip_tipo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='fundamentacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='objetivos_generales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='objetivos_especificos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='competencias',
            field=models.TextField(blank=True),
        ),
    ]
