# Generated by Django 5.2.8 on 2025-12-12 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(help_text='Código único para identificar la carrera', max_length=20, unique=True)),
                ('nivel', models.CharField(choices=[('PG', 'Pregrado'), ('G', 'Grado')], default='G', help_text='Nivel de la carrera (Pregrado o Grado)', max_length=5)),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'carreras',
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_por_cre', models.PositiveIntegerField(default=25, help_text='Número predeterminado de horas CRE asignadas a cada carrera')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración CRE',
                'db_table': 'configuracion_cre',
            },
        ),
        migrations.CreateModel(
            name='EspacioCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único para identificar el espacio curricular', max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_espacio', models.CharField(choices=[('T1', 'T1 - Asignaturas'), ('T2', 'T2 - Seminarios'), ('T3', 'T3 - Talleres y laboratorios'), ('T4', 'T4 - Actividades profesionales especiales')], help_text='Tipo de espacio curricular', max_length=3)),
                ('anio_cursada', models.PositiveSmallIntegerField(help_text='Año de cursada del espacio curricular dentro del plan de estudio', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('periodo', models.CharField(choices=[('ANUAL', 'Anual'), ('1S', '1er Semestre'), ('2S', '2do Semestre')], help_text='Período en el que se dicta el espacio curricular', max_length=5)),
                ('creditos', models.PositiveIntegerField(help_text='Número de créditos asignados al espacio curricular', validators=[django.core.validators.MinValueValidator(1)])),
                ('horas_ip', models.PositiveIntegerField(help_text='Número de horas de Interacción Pedagógica (IP) del espacio curricular', validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_ta', models.PositiveIntegerField(help_text='Número de horas de trabajo autónomo (TA) del espacio curricular', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'espacio curricular',
                'verbose_name_plural': 'espacios curriculares',
                'db_table': 'espacio_curricular',
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(help_text='Código único para identificar la unidad académica', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'unidad académica',
                'verbose_name_plural': 'unidades académicas',
                'db_table': 'unidad_academica',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ordenanza', models.CharField(help_text='Ordenanza que aprueba el plan de estudio', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.PositiveIntegerField(help_text='Número total de créditos del plan de estudios', validators=[django.core.validators.MinValueValidator(1)])),
                ('vigente_desde', models.DateField(help_text='Fecha desde la cual el plan de estudio está vigente')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual el plan de estudio estuvo vigente (dejar en blanco si aún está vigente)', null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='academics.carrera')),
            ],
            options={
                'verbose_name': 'plan de estudio',
                'verbose_name_plural': 'planes de estudio',
                'db_table': 'plan_estudio',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudioEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio_curricular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.espaciocurricular')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.planestudio')),
            ],
            options={
                'verbose_name': 'plan de estudio - espacio curricular',
                'verbose_name_plural': 'planes de estudio - espacios curriculares',
                'db_table': 'plan_estudio_espacio_curricular',
            },
        ),
        migrations.AddField(
            model_name='planestudio',
            name='espacios_curriculares',
            field=models.ManyToManyField(related_name='planes_estudio', through='academics.PlanEstudioEC', to='academics.espaciocurricular'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='academics.unidadacademica'),
        ),
        migrations.AddConstraint(
            model_name='planestudioec',
            constraint=models.UniqueConstraint(fields=('plan_estudio', 'espacio_curricular'), name='unique_plan_estudio_ec'),
        ),
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(fields=('carrera', 'nombre'), name='unique_plan_estudio_carrera'),
        ),
    ]
