# Generated by Django 5.2.8 on 2025-12-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_por_cre', models.PositiveIntegerField(default=25, help_text='Número predeterminado de horas CRE asignadas a cada carrera')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración CRE',
                'db_table': 'configuracion_cre',
            },
        ),
        migrations.AlterField(
            model_name='facultad',
            name='sigla',
            field=models.CharField(help_text='Código único para identificar la facultad', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(help_text='Código único para identificar la carrera', max_length=20, unique=True)),
                ('nivel', models.CharField(choices=[('PG', 'Pregrado'), ('G', 'Grado')], default='G', help_text='Nivel de la carrera (Pregrado o Grado)', max_length=5)),
                ('creditos', models.PositiveIntegerField(help_text='Número total de créditos requeridos para completar la carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='academics.facultad')),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'carreras',
                'db_table': 'carrera',
            },
        ),
    ]
