# Generated by Django 6.0.2 on 2026-02-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciocurricular',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Código único para identificar el espacio curricular', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='espaciocurricular',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
