# Generated by Django 5.2.8 on 2025-12-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_configuracioncre_alter_facultad_sigla_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vigente_desde', models.DateField(help_text='Fecha desde la cual el plan de estudio está vigente')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual el plan de estudio estuvo vigente (dejar en blanco si aún está vigente)', null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='academics.carrera')),
            ],
            options={
                'verbose_name': 'plan de estudio',
                'verbose_name_plural': 'planes de estudio',
                'db_table': 'plan_estudio',
                'unique_together': {('carrera', 'nombre')},
            },
        ),
    ]
