# Generated by Django 6.0.2 on 2026-03-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_espaciocurricular_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Codigo identificador de la competencia dentro del plan', max_length=50)),
                ('nombre', models.CharField(help_text='Nombre de la competencia', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion detallada de la competencia', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Indica si la competencia esta activa (baja logica)')),
                ('plan_estudio', models.ForeignKey(help_text='Plan de estudio al que pertenece la competencia', on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='academics.planestudio')),
            ],
            options={
                'verbose_name': 'competencia',
                'verbose_name_plural': 'competencias',
                'db_table': 'competencia',
                'ordering': ['plan_estudio_id', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('plan_estudio', 'codigo'), name='unique_competencia_plan_codigo')],
            },
        ),
    ]
