# Generated by Django 5.2.8 on 2025-12-01 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_planestudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único para identificar el espacio curricular', max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_espacio', models.CharField(choices=[('T1', 'T1 - Asignaturas'), ('T2', 'T2 - Seminarios'), ('T3', 'T3 - Talleres y laboratorios'), ('T4', 'T4 - Actividades profesionales especiales')], help_text='Tipo de espacio curricular', max_length=3)),
                ('anio', models.PositiveSmallIntegerField(help_text='Año en el que se dicta el espacio curricular dentro del plan de estudio')),
                ('periodo', models.CharField(choices=[('ANUAL', 'Anual'), ('1S', '1er Semestre'), ('2S', '2do Semestre')], help_text='Período en el que se dicta el espacio curricular', max_length=5)),
                ('creditos', models.PositiveIntegerField(help_text='Número de créditos asignados al espacio curricular')),
                ('horas_ip', models.PositiveIntegerField(help_text='Número de horas de Interacción Pedagógica (IP) del espacio curricular')),
                ('horas_ta', models.PositiveIntegerField(help_text='Número de horas de trabajo autónomo (TA) del espacio curricular')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_curriculares', to='academics.planestudio')),
            ],
            options={
                'verbose_name': 'espacio curricular',
                'verbose_name_plural': 'espacios curriculares',
                'db_table': 'espacio_curricular',
                'unique_together': {('plan_estudio', 'codigo')},
            },
        ),
    ]
