#!/bin/sh
set -eu

# APP_DB_PASSWORD is an ephemeral hex value generated by run.sh, never a
# production credential. Hex contains no SQL quoting characters.
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE ROLE creapp_usr LOGIN CREATEDB PASSWORD '$APP_DB_PASSWORD';
CREATE DATABASE creapp_db OWNER creapp_usr ENCODING 'UTF8';
SQL
